version: '3'
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - "27017:27017"

    webserver:
        image: flask
        container_name: webserver
        restart: always
        ports:
            - "5000:5000"
